#! /usr/bin/bash
shopt -s extglob
export LC_COLLATE=C

function main_menu() {
    
    # Give the user a menu to create, drop, or connect to a database
    select i in CreateDB ListDB DropDB ConnectDB Exit
    do
        case $i in
            "CreateDB")
                while true; do
                    read -p "Please Enter Database Name: " DBNAME
                    if [ -e "$DBNAME" ]; then
                        echo "Database is already exist"
                    else
                        case $DBNAME in
                            [0-9]*) # starts with number
                                echo "db name can't start with a number"
                                ;;
                            " "*)  # Starts with a space
                                echo "db name can't start with a space"
                                ;;
                            *" "*)  # Contains a space
                                echo "db name can't have spaces"
                                ;;
                            +([a-zA-Z0-9]))
                                mkdir "$DBNAME"
                                echo ""
                                echo "$DBNAME database created succefully"
                                echo ""
                                main_menu
                                break
                                ;;
                            *) # for regex
                                echo "db name name can't have regex and start only with letters"
                                ;;
                        esac
                    fi
                done
                ;;
            "ListDB")
                # List all databases and replace / with nothing
                echo "Databases List:"
                echo ""
                ls -F | grep / | sed 's/\/$//'
                echo ""
                main_menu
                ;;
            "DropDB")
                read -p "Please Enter Database Name: " DBNAME
                if [ -e "$DBNAME" ]; then
                    rm -r "$DBNAME"
                    echo ""
                    echo "$DBNAME database removed"
                    echo ""
                    main_menu
                else
                    echo "Database does not exist"
                fi
                ;;
            "ConnectDB")
                read -p "Please Enter Database Name: " DBNAME
                if [ -e "$DBNAME" ]; then
                    cd "$DBNAME" || exit
                    echo ""
                    echo "Connected to $DBNAME successfully"
                    echo ""

    #################### Start to show tables options (Create Select Insert Update Delete every option should be a separate script )
                    connect_menu

                else
                    echo "Database does not exist"
                fi
                ;;
            "Exit")
                    echo "exit DBENGINE..."
                    exit 0
                 ;;
            *)
                echo "Please enter a valid choice"
                ;;
        esac
    done
}

function connect_menu() {
    select j in Create_table List_tables Drop_tables Select Insert Update Delete Back
                    do
                        case $j in
                            # create two files for each table
                            "Create_table")
                                source ../../create_table                # run script of creating table                
                                ;;
                            "List_tables")
                                echo "Tables List:"
                                ls -F | grep -v "_metadata$"
                                ;;	
                            "Drop_tables")
                                read -p "Please Enter Table Name: " TBNAME
                                if [[ $(basename "$TBNAME" | tail -c 10) == "_metadata" ]]; then
                                    echo "table does not exist"
                                else
                                    if [ -e "$TBNAME" ]; then
                                        rm "$TBNAME";
                                        rm "$TBNAME"_metadata
                                        echo "$TBNAME table removed"
                                    else
                                        echo "table does not exist"
                                    fi
                                fi
                                ;;
                            "Select")
                                source ../../select
                                ;;	 
                            "Insert")
                                source ../../insert
                                ;; 
                            "Update")
                                source ../../update
                                ;;
                            "Delete")
                                source ../../delete
                                ;;
                            "Back")
                                    cd ..
                                    main_menu
                                    break
                                ;;
                            *)
                                echo "Please enter a valid choice"
                                ;;
                        esac
                    done
}

read -p "Please Enter Table Name: " TBNAME
if [ -e "$TBNAME" ]; then 
    # loop for each column in the table
    table="$TBNAME"_metadata # variable to pass to awk
    values="" # array to hold inserted values
    IFS=$'\n' # set Internal Field Separator to newline for the loop
    row_no=1 #to track the columns

    for column_info in $(cut -f1,2,3 -d: "$table"); do
        # split column_info into name, type, and pk_value
        IFS=':' read -r column_name column_type pk_value <<< "$column_info"

        while true; do
            read -p "Enter the value of $column_name (type $column_type): " value
            #check for uniqueness if PK
            if [ "$pk_value" -eq 1 ]; then
                table_name="$TBNAME"
                if awk -v value="$value" -v row_no="$row_no" -F: '$row_no == value { found=1; exit } END { exit !found }' "./$table_name"
                then
                    echo "PK value cannot be repeated, insert another value."
                else 
                    # check if the value is an integer or string based on the column type
                    if [ "$column_type" == "int" ]; then
                        if [[ "$value" =~ ^-?[0-9]+$ ]]; then
                            values+=":$value"
                            break
                        else
                            echo "Invalid input. Please enter an integer for $column_name."
                        fi
                    elif [ "$column_type" == "string" ]; then
                        case $value in
                            +([a-zA-Z||" "]))
                                values+=":$value"
                                break
                                ;;
                        *)
                            echo "Invalid input. Please enter a string with only letters and spaces for $column_name."
                        esac
                    fi

                fi
            elif [ "$pk_value" -eq 0 ]; then
                # check if the value is an integer or string based on the column type
                if [ "$column_type" == "int" ]; then
                    if [[ "$value" =~ ^-?[0-9]+$ ]]; then
                        values+=":$value"
                        break
                    else
                        echo "Invalid input. Please enter an integer for $column_name."
                    fi
                elif [ "$column_type" == "string" ]; then
                    case $value in
                            +([a-zA-Z||" "]))
                            values+=":$value"
                                break
                                ;;
                        *)
                            echo "Invalid input. Please enter a string with only letters and spaces for $column_name."
                        esac
                fi
            fi
        done
        (( row_no++ )) #number of the upcoming column   
    done
    # insert values in table
    echo "${values:1}" >> "./$TBNAME"
    echo ""
    echo "values ${values:1} inserted successfully"
    echo ""
    connect_menu
    # Reset IFS to default (space, tab, newline)
    IFS=$' \t\n'
else
    echo ""
    echo "Table does not exist: $TBNAME"
    echo ""
    connect_menu
fi


